public class SQLScripts {
    public String createCountries = "CREATE TABLE COUNTRIES (ID SERIAL PRIMARY KEY NOT NULL, NAME TEXT NOT NULL, CODE TEXT NOT NULL, CONTINENT TEXT NOT NULL)";
    public String createContinents = "CREATE TABLE CONTINENTS (ID SERIAL PRIMARY KEY NOT NULL, NAME TEXT NOT NULL)";
    public String createCities = "CREATE TABLE CITIES (ID SERIAL PRIMARY KEY NOT NULL, COUNTRY TEXT NOT NULL, NAME TEXT NOT NULL, CAPITAL BOOLEAN NOT NULL, LATITUDE NUMERIC(19,15) NOT NULL, LONGITUDE NUMERIC(19,15) NOT NULL)";
}
